### ISSUE TITLE
Jump to SHA in repo

### ISSUE THREAD

**Issue by jnross** [fork-dev/Docs#1]
I'm a recent convert from SourceTree.  I'm mostly pleased with the change, but still getting my bearings.  Is there a way to jump to a commit SHA in a repo?

**Comment by Otiel** [comment]
Welcome!

You can either use the search field (Ctrl+F), or quicker, use the command palette: Ctrl+P then paste your SHA.

**Comment by jnross** [comment]
Oh my, I didn't even notice the response here from months ago until Dan closed this ticket today.  Thanks @Otiel for the tips!  I didn't know about Ctrl+F.  I was trying to search in the left pane and was having no luck:
<img width="295" alt="Screen Shot 2022-02-22 at 8 40 50 AM" src="https://user-images.githubusercontent.com/798990/155178119-cc670307-5c90-4c4c-a7af-07f30f996a92.png">
Although Ctrl-F does work and I found the commit I was looking for, Ctrl+P found no matches:
<img width="618" alt="Screen Shot 2022-02-22 at 8 43 17 AM" src="https://user-images.githubusercontent.com/798990/155178299-117486bf-5e5f-4948-9fd7-5173a7b40648.png">

**Comment by Otiel** [comment]
That is not normal, I don't see a possible situation where the commit can be found using Ctrl+F, but not using Ctrl+P. 🤔

The only limitation I know with Ctrl+P is that you need to type a minimum number of characters (6 I think, need to check) in order to start searching.

Maybe the Mac version has a different behavior than the Windows one, @DanPristupov?
